---
# handlers file for ansible-samba
- name: restart smbd
  service:
    name: "smbd.service"
    state: restarted

    #- name: restart samba-ad-dc
  #  service:
          #    name: "samba-ad-dc"
    #    state: restarted
              
- name: restart nmbd
  service:
    name: "nmbd.service"
    state: restarted
