---
- name: "DevOps toolbox"
  #  hosts: kal-xt3
  apt: name={{item}} state=latest
  with_items:
    - ansible
    - mysql-workbench
    - rhc
      #    - ansible-tower-cli
    - packer
    - vim-syntax-docker
    - systemd-docker
    - whalebuilder
    - docker-compose
    - ctop
    - cockpit-docker
    - vim-syntax-docker
    - docker.io
    - vagrant
    - virtualbox
    - virt-goodies
    - xclip
    - xsel
    - runsnakerun
    - python3-pprofile
    - kcachegrind
    - kcachegrind-converters
    - pyprof2calltree
