---
- name: DevOps toolbox
  apt: name={{ item }} state=latest
  loop:
    - ansible 
      #    - ansible-tower-cli
    - packer
    - vim-syntax-docker
    - whalebuilder
    - docker-compose
    - ctop
    - vim-syntax-docker
    - docker.io
    - vagrant
    - virtualbox
      #    - virt-goodies
    - xclip
    - xsel
    - runsnakerun
    - python3-pprofile
    - kcachegrind
    - kcachegrind-converters
    - pyprof2calltree
    - azure-cli
    - awscli
      #    - puppetserver

- name: Python utils
  pip: 
    name={{ vars}} 
    state=latest
  loop:
    - flask
    - flask_sqlalchemy
    - flask_migrate
    - flask_cors
