---
- name: DevOps toolbox
  apt: name={{ items }} state=latest
  vars:
    items:
    - ansible 
    - rhc
      #    - ansible-tower-cli
    - packer
    - vim-syntax-docker
    - whalebuilder
    - docker-compose
    - ctop
    - vim-syntax-docker
    - docker.io
    - vagrant
    - virtualbox
    - virt-goodies
    - xclip
    - xsel
    - runsnakerun
    - python3-pprofile
    - kcachegrind
    - kcachegrind-converters
    - pyprof2calltree
    - azure-cli
    - awscli
