---
- name: Desktop apps
  apt: name={{item}} state=latest
  with_items:
    - transmission
    - libreoffice
    - konversation
    - evolution

- name: Install Snap apps
  command: "snap install pycharm-community" 
  #with_items:
            #      - {{item}} #state=present
        #    with_items:
        #      - 'pycharm-community'
  register: my_snap
- name: System utils
  apt: name={{item}} state=latest
  with_items:
    - lvm2
    - rsync
    - htop
    - ansible
    - ctop
    - virt-goodies
    - virt-manager
    - virt-top
    - virtinst
    - docker.io
    - docker
    - mysql-utilities
  ignore_erros: True
  register: result
- name: Dev utils
  apt: name={{item}} state=latest
  with_items:
    - python3-pip
    - idle3
    - retext
    - python3
    - mysql-workbench
    - vim-syntax-docker
    - python3-pip
  ignore_errors: True
- name: DevOps Utils
  apt: name={{item}} state=latest
  with_items:
    - ansible-lint
    - multipath-tools
    - ansible-tower-cli
  ignore_errors: True
  register: result
- name: "hosts file"
  blockinfile: 
    dest: /etc/hosts 
    block: |
     # Ansible populated
      10.42.0.203        kal-xt3    kal-xt3.kal-net.com
      10.42.0.2          kalibur-mce    kalibur-mce.kal-net.com
      10.42.0.30         kal-bunker    kal-bunker.kal-net.com
      10.42.0.80         kal-ninja   kal-ninja.kal-net.com
      10.42.0.53         ipa01    ipa01.kal-net.com
      #    state: present 
    backup: yes 
    #    create: yes
