---
- name: Desktop apps
  apt: name={{items}}  state=latest
  vars:
    items:
    - transmission
    - libreoffice
    - konversation
    - evolution

- name: Install Snap apps
  snap:  
    state: present 
    classic: yes
  #  vars:
  #  shell:
  # cmd: sudo snap install {{items}} --classic
  # vars:
    name:
            #      - mysql-workbench
      - pycharm-community
      - jupyter
      - code
      - atom
  register: my_snap
  ignore_errors: false

- debug:
    msg: my_snap  

- name: System utils
  apt: name={{items}} state=latest
  vars:
    items:
    - lvm2
    - rsync
    - htop
    - ansible
    - ctop
    - virt-goodies
    - virt-manager
    - virt-top
    - virtinst
    - docker.io
    - docker
    - mysql-utilities
    - fakeroot
  ignore_errors: True
  register: result
- name: Dev utils
  apt: name={{items}} state=latest
  vars:
    items:
    - python3-pip
    - python-pip
    - idle3
    - libmysqlclient-dev
    - default-libmysqlclient-dev
    - retext
    - python3
    - python3-dev
      #    - mysql-workbench
      # - vim-syntax-docker
    - python3-pip
  ignore_errors: True
- name: Pip installs
  pip:  name={{items}} state=latest executable=pip3
  vars:
    items:
    - Mediainfo
    - pymediainfo
    - pymiparse
    - ansible-playbook-grapher
    - ansible-inventory-grapher
    - gperf
    - sadf
    - gperf
    - virtualenv
    - virtualenvwrapper
    - pytz
    - django
    - pymysql
    - django-mysql-pymysql
    - pymysql-utils
    - mysqlclient
    - paramiko
    - matplotlib
    - pandas
    - jupyter
    - wordcloud
    - fileupload
    - ipywidgets

- name: DevOps Utils
  apt: name={{items}} state=latest
  vars:
    items:
    - ansible-lint
    - multipath-tools
    - ansible-tower-cli
  ignore_errors: True
  register: result
- name: "hosts file"
  blockinfile: 
    dest: /etc/hosts 
    block: |
     # Ansible populated
      10.42.0.206        kal-inspiron    kal-inspiron.kal-net.home
      10.42.0.215        kal-xt3    kal-xt3.kal-net.home
      10.42.0.2          kalibur-mce    kalibur-mce.kal-net.home
      10.42.0.30         kal-bunker    kal-bunker.kal-net.home
      10.42.0.80         kal-ninja   kal-ninja.kal-net.home
      10.42.0.89         ipa01    ipa01.kal-net.home
      10.42.0.201        mac-rhel  mac-rhel.kal-net.home
      #    state: present 
    backup: yes 
    #    create: yes
- name: Security
  apt: name={{items}} state=latest
  vars:
    items:
      - firewalld
  ignore_errors: True
  notify: 
    - firewalld reload 

- name: Handlers
  systemd: 
    name: firewalld    
    state: started 
    enabled: yes
