---
- name: Desktop apps
  apt: 
   name: "{{items}}" 
   state: latest
  vars:
    items:
    - transmission
    - libreoffice
    - konversation
    - evolution

- name: Install Snap apps
  snap:
    name:
      - mysql-workbench
      - pycharm-community
      - jupyter
    classic: yes
    
  register: my_snap
  ignore_errors: True
- debug:
    msg: my_snap  
- name: System utils
  apt: name={{items}} state=latest
  vars:
    items:
    - lvm2
    - rsync
    - htop
    - ansible
    - ctop
    - virt-goodies
    - virt-manager
    - virt-top
    - virtinst
    - docker.io
    - docker
    - mysql-utilities
    - fakeroot
  ignore_errors: True
  register: result
- name: Dev utils
  apt: name={{items}} state=latest
  vars:
    items:
    - python3-pip
    - python-pip
    - idle3
    - retext
    - python3
      #    - mysql-workbench
      # - vim-syntax-docker
    - python3-pip
  ignore_errors: True
- name: Pip installs
  pip:  name={{items}} state=latest executable=pip3
  vars:
    items:
    - Mediainfo
    - pymediainfo
    - pymiparse
    - ansible-playbook-grapher
    - ansible-inventory-grapher
    - gperf
    - sadf
    - gperf
    - paramiko
    - matplotlib
    - pandas
    - jupyter

- name: DevOps Utils
  apt: name={{items}} state=latest
  vars:
    items:
    - ansible-lint
    - multipath-tools
    - ansible-tower-cli
  ignore_errors: True
  register: result
- name: "hosts file"
  blockinfile: 
    dest: /etc/hosts 
    block: |
     # Ansible populated
      10.42.0.206        kal-inspiron    kal-inspiron.kal-net.com
      10.42.0.203        kal-xt3    kal-xt3.kal-net.com
      10.42.0.2          kalibur-mce    kalibur-mce.kal-net.com
      10.42.0.30         kal-bunker    kal-bunker.kal-net.com
      10.42.0.80         kal-ninja   kal-ninja.kal-net.com
      10.42.0.53         ipa01    ipa01.kal-net.com
      10.42.0.201        mac-rhel  mac-rhel.kal-net.com
      #    state: present 
    backup: yes 
    #    create: yes
- name: Security
  apt: name={{items}} state=latest
  vars:
    items:
      - firewalld
  ignore_errors: True
  notify: 
    - firewalld reload 

- name: Handlers
  systemd: 
    name: firewalld    
    state: started 
    enabled: yes
