---
- name: Desktop apps
  apt: name={{item}} state=latest
  with_items:
          #    - eclipse
    - idle3
    - transmission
    - libreoffice
    - python3
    - konversation
- name: System utils
  apt: name={{item}} state=latest
  with_items:
    - lvm2
    - rsync
    - htop
    - ansible
    - ctop
    - virt-goodies
    - virt-manager
    - virt-top
    - virtinst
    - docker.io
    - docker
    - mysql-utilities
  ignore_erros: True
  register: result
- name: Dev utils
  apt: name={{item}} state=latest
  with_items:
    - python3-pip
    - idle3
    - mysql-workbench 
    - vim-syntax-docker
    - python3-pip
- name: DevOps Utils
  apt: name={{item}} state=latest
  with_items:
    - ansible-lint
    - multipath-tools
    - ansible-tower-cli
  ignore_errors: True
  register: result
- name: "hosts file"
  blockinfile: 
  #path: /etc/hosts 
    dest: /etc/hosts 
    #    regex: 
    block: |
     # Ansible populated
      10.42.0.203        kal-xt3    kal-xt3.kal-net.com
      10.42.0.3          kalibur-mce    kalibur-mce.kal-net.com
      10.42.0.30         kal-bunker    kal-bunker.kal-net.com
      10.42.0.80         kal-ninja   kal-ninja.kal-net.com
      10.42.0.53         ipa01    ipa01.kal-net.com
      #    state: present 
    backup: yes 
    #    create: yes
