---
- name: Desktop apps
  apt: 
    name: "{{ item }}" 
    state: latest
  loop:
    - transmission
    - libreoffice
    - konversation
    - evolution

- name: Install Snap apps
  snap:  
    state: present 
    classic: yes
    name:
      - pycharm-community
      - jupyter
      - code
      - atom
      - photogimp
      - gimp
      - inkscape
      - google-cloud-sdk

  register: my_snap
  ignore_errors: true
  #- name: Remove snap terraform
  # snap: name=terraform state=absent

- debug:
    msg: my_snap  
- name: Add apt Key terraform
  shell: 'sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -'
  ignore_errors: yes

- name: System utils
  apt: name={{items}} state=latest
  vars:
    items:
    - lvm2
    - elinks
    - rsync
    - htop
    - ansible
    - virt-manager
    - virt-top
    - virtinst
    - docker.io
    - fakeroot
      #- terraform
  ignore_errors: True
  register: result
- name: Dev utils
  apt: name={{items}} state=latest
  vars:
    items:
    - idle3
    - libmysqlclient-dev
    - default-libmysqlclient-dev
    - retext
    ignore_errors: True

- name: DevOps Utils
  apt: name="{{item}}" state=latest
  loop:
    - ansible-lint
    - multipath-tools
  ignore_errors: True
  register: result

- name: Remove dirty hosts file
  lineinfile:
    dest: /etc/hosts 
    regex: "^#.*ANSIBLE MANAGED.*$"
    state: absent

- name: Etc hosts file
  lineinfile:
    state: present
    insertafter: EOF
    backup: true
    dest: /etc/hosts
    regex: '"{{ item.host }}"\s'
    line: "{{ item.ip }} {{ item.host }} {{ item.alias }}"
  loop:
    - { ip: '10.42.0.201', host: kal-inspiron, alias: 'kal-inspiron.kal-net.home' }
    - { ip: '10.42.0.215', host: kal-xt3,    alias: 'kal-xt3.kal-net.home' }
    - { ip: '10.42.0.22', host: kal-zen,    alias: 'kal-zen.kal-net.home' }
    - { ip: '10.42.0.2', host: kalibur-mce,    alias: 'kalibur-mce.kal-net.home' }
    - { ip: '10.42.0.30', host: kal-bunker,    alias: 'kal-bunker.kal-net.home' }
    - { ip: '10.42.0.25', host: kal-bunker2,    alias: 'kal-bunker2.kal-net.home' }
    - { ip: '10.42.0.8', host:  kalimg,      alias: 'kalimg.kal-net.home' }
    - { ip: '10.42.0.40', host: kal-5825u, alias: 'kal-5825u.kal-net.home' }

- name: Debugging and troubleshooting tools
  apt: name={{pkgs}} state=latest
  vars:
     pkgs:
       - systemtap-sdt-dev
       - linux-tools-common 
       - apache2-utils
       - atop

- name: Security
  apt: name={{items}} state=latest
  vars:
    items:
      - firewalld
  ignore_errors: True
  notify: 
    - firewalld reload 

- name: Handlers
  systemd: 
    name: firewalld    
    state: started 
    enabled: yes
