---
  tasks:
    - name: Pip install django-framwork
      pip: name={{packages}} state=latest
      vars:
        packages:
          - Django

    - name: Authentication utils
      apt: name={{packages}} state=latest
      vars:
        packages:
          - apache2-utilso
          - nginx-extras
