---
work_group: "KAL-NET"
server_string : '%h samba share server  (Samba, Ubuntu)'
usershare_allow_guests : "yes"
security: "user"

samba_shares:
- name: Movies
  comment: 'Movies and Films'
  directory: '/media/'
  browseable: "yes"
  folder_perms: "755"
  group: kalibur
  guest_ok: "yes"
  owner: kalibur
  read_only: "yes"
  writable: "yes"
  force_user: "kalibur"

- name: audios
  comment: 'Music, Audiobooks, etc'
  directory: '/media/'
  browseable: "yes"
  folder_perms: "755"
  group: kalibur
  guest_ok: "yes"
  owner: kalibur
  read_only: "yes"
  writable: "no"

- name: incoming
  comment: 'Fresh arrivals'
  directory: '/media/'
  browseable: "yes"
  folder_perms: "755"
  group: kalibur
  guest_ok: "yes"
  owner: kalibur
  read_only: "yes"
  writable: "no"
