---
work_group: 'KALNET'
server_string : '%h - %D samba share server '
usershare allow guests : yes
security: user
samba_shares:
  - name: Movies
    comment: Movies and Films
    directory: /media/movies/Films
    folder_perms: "0755"
    group: kalibur
    guest_ok: "yes"
    browsable: "yes"
    owner: kalibur
    read_only: "yes"
    writable: "no"
    allow_guests: yes
  - name: Audios
    comment: Music, Audiobooks, etc
    directory: /media/audios
    browsable: "yes"
    folder_perms: "0755"
    group: kalibur
    guest_ok: "yes"
    owner: kalibur
    read_only: "yes"
    writable: "no"
    allow_guests: yes
    #  - name: Audios
