---
work_group: 'KALNET'
server_string : '%h samba share server  (Samba, Ubuntu)'
usershare_allow_guests : yes
security: user
samba_shares:
- name: Films
  comment: 'Movies and Films'
  directory: '/media/movies/'
  folder_perms: "0755"
  group: kalibur
  guest_ok: "yes"
  browsable: "yes"
  owner: kalibur
  read_only: "yes"
  writable: "no"
  allow_guests: yes


- name: Audios
  comment: 'Music, Audiobooks, etc'
  directory: '/media/'
  browsable: "yes"
  folder_perms: "0755"
  group: kalibur
  guest_ok: "yes"
  owner: kalibur
  read_only: "yes"
  writable: "no"
  allow_guests: yes
