---
- name: setup samba and shares for MCE
  template: 
    src: 'etc/samba/smb.conf.j2'
    dest: '/etc/samba/smb.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
    force: yes
    register: smb_conf

- debug:
    var: smb_config
    
  notify:
    - restart nmbd
    - restart smbd
-
