---
- name: Install glusterfs client utils
  apt: name={{item}} state=latest
  vars:
    item:
    - glusterfs-client
    - glusterfs-common
    - nfs-ganesha
    - nfs-ganesha-gluster
    - uwsgi-plugin-glusterfs

      #- name: Volume mounts


- name: Firewall config
  shell: "firewall-cmd --add-service={{item}} --permanent"
  with_items:
    - 'http'
    - 'nfs'
    - 'samba'
    - 'ntp'
    - 'ldap'
    - 'ldaps'
    - 'dns'
    - 'mdns'
    - 'samba-client'
    - 'https'
    - 'mountd'
    - 'glusterfs'
      #    - 'rpc-bind'
      #    - 'rpc2portmap'
- name: Firewall ports allow
  shell: "firewall-cmd --add-port={{ item }} --permanent"
  with_items:
    - '8080/tcp'
    - '8080/udp'
    - '445/tcp'
    - '88/tcp'
    - '45000-50000/tcp'
    - '2049/tcp'
    - '111/udp'
    - '963/udp'
    - '139/tcp'
    - '389/udp'
    - '389/tcp'
    - '369/udp'
    - '369/tcp'
    - '24007-24100/tcp'
    - '111/tcp'
    - '464/tcp'
    - '965/tcp'
    - '24007-24100/udp'
    - '45000-50000/udp'

- name: Reload firewalld  
  shell: "firewall-cmd --reload"
  #    - firewalld reload
  ignore_errors: True
