---
- name: Install glusterfs client utils
  apt: name={{item}} state=latest
  with_items:
    - glusterfs-client
    - glusterfs-common

      #- name: Volume mounts


- name: Firewall config
  shell: "firewall-cmd --add-service={{item}} --permanent"
  with_items:
    - 'http'
    - 'nfs'
    - 'samba'
    - 'ntp'
    - 'dns'
    - 'samba-client'
    - 'https'
- name: Firewall ports allow
  shell: "firewall-cmd --add-port={{item}} --permanent"
  with_items:
    - '8080/tcp'
    - '8080/udp'
    - '445/tcp'
    - '88/tcp'
    - '49000-49251/tcp'
    - '2049/tcp'
    - '111/udp'
    - '963/udp'
    - '139/tcp'
    - '389/tcp'
    - '389/tcp'
    - '369/udp'
    - '369/udp'
    - '2400-24100/tcp'
    - '111/tcp'
    - '464/tcp'
    - '965/tcp'
    - '24007-24008/tcp'
    - '49000-49500/udp'

    -
- name: Reload firewalld
  shell: "firewall-cmd --reload"
