---
- name: setup samba and shares for MCE
  #  hosts: mce
  template: 
    src: etc/samba/smb.conf.j2 
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nmbd
    - restart smbd
    

