---
- name: "DevOps toolbox"
  hosts: kal-xt3
  apt: name={{item}} state=latest
  with_items:
    - ansible
    - rhc
      #    - ansible-tower-cli
    - packer
    - vim-syntax-docker
    - systemd-docker
    - whalebuilder
    - docker-compose
    - ctop
    - cockpit-docker
    - vim-syntax-docker
    - docker.io
    - vagrant
    - virtualbox
    - virt-goodies
    - xclip
    - python3-pip
