---
# tasks file for roles/minikube
- name:  Install dependancies
  package:
    name: "{{ item }}"
    state: latest 
  loop:
    - curl
    - apt-transport-https
    - ca-certificates
- name: Ensure we have /etc/opt/keyrings
  file:
    state: directory
    dest: /etc/opt/keyrings
    mode: 0755

- name: Install keyring things
  command: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && chmod a+r /etc/apt/keyrings/docker.asc'

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  command: '#echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'

- name: Add Docker repository
  apt_repository:
     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu/dists/ $(lsb_release -cs) stable stable"
     state: present

- name: Update package lists again
  apt: 
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add user to Docker group (optional)
  user:
    name: "kalibur" # Who is ansible_user ??
    groups: docker
    append: yes
  ignore_errors: true

- name: Download Minikube binary
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /tmp/minikube-linux-amd64
    mode: 0755

- name: Install Minikube
  copy:
    src: /tmp/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: 0755

- name: Download kubectl binary
  get_url:
    url: https://storage.googleapis.com/kubernetes/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
    dest: /tmp/kubectl
    mode: 0755
- name: Create directory for kubectl if needed
  file:
    name: /usr/local/bin
    state: directory
    mode: 0755
  register: result

- name: Set permissions and move kubectl binary
  command:  chmod +x /tmp/kubectl && mv /tmp/kubectl /usr/local/bin/
  when: result.rc == 0

- name: Start Minikube
  command: 'minikube start'

- name: Restart Docker after adding user to group
  service:
    name: docker
    state: restarted
  when: changed
