---
#- name: Install MythTV
  #  apt_repository: 
  #   repo: 'ppa:team-xbmc/ppa'  
  #   state: present
  #   validate_certs: yes 
  #   update_cache: yes
     #- name: Remove ubuntu repo Kodi
     #  apt: name={{items}} state=absent
- name: Install kodi
  apt: name={{item}} state=latest
  with_items:
#- name: Firewall config
  # not support due to this module using python2
  # firewalld: service={{item}} permanent=yes immediate=yes state=enabled
  #shell: "firewall-cmd --add-service={{item}} --permanent"
  #with_items:
  #  - 'http'
  
- name: restart firewalld
  service: name=firewalld state=reloaded
- name: Apt install mythv
  apt: name={{item}} state=present
  with_items:
    - mythtv
