---
work_group: 'KAL-NET'
server_string : '%h samba share Kal-net'
usershare_allow_guests : "yes"
security: "user"

samba_shares:
- name: Videos
  comment: 'Movies and Films'
  directory: '/home/kalibur/Videos'
  browseable: "yes"
  folder_perms: "0755"
  guest_ok: "yes"
  read_only: "yes"
